/**
  ******************************************************************************
  * File Name          : topology.h
  * Date               : 12-Aug-2015
  *	Author 			   : Asaad Kaadan
  * Description        : This file is automatically generated by the 'topogen' MATLAB tool.
  *                      This version is compiled for MOWE-Tandy simulator use.
  *
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include <stdint.h>

// Module Part Numbers:
// HO01R1: Hexagon receiver with VEMT3700 - 30mm optical resolution.
// HO01R2: Hexagon receiver with VEMT3700 - 20mm optical resolution.
// HO02R0: Hexagon transmitter  with VSMY2850G - 30mm optical resolution.
// HO02R1: Hexagon transmitter  with VSMY2850G - 20mm optical resolution.
// PO01R0: Pentagon receiver with VEMT3700 compatible with hexagons 30mm optical resolution.
// PO02R0: Pentagon transmitter  with VSMY2850G compatible with hexagons 30mm optical resolution.

// Enumerations
enum	modulePartNumbers{_HO01R1, _HO01R2, _HO02R0, _HO02R1, _PO01R0, _PO02R0};
enum	portPol{_normal, _reversed};
enum	modulePorts{_P1=1, _P2, _P3, _P4, _P5, _P6};

#define _N	7					// Number of array modules

#define portCount	6

// Array modules
#define _mod1	1<<8
#define _mod2	2<<8
#define _mod3	3<<8
#define _mod4	4<<8
#define _mod5	5<<8
#define _mod6	6<<8
#define _mod7	7<<8

// Topology
static uint16_t array[_N][7] = {
{ _HO01R1, _mod6|_P4, _mod5|_P5, _mod4|_P6, _mod3|_P1, _mod2|_P2, _mod7|_P3},	// Module 1
{ _HO01R1, _mod7|_P4, _mod1|_P5, _mod3|_P6, 0, 0, 0},	// Module 2
{ _HO01R1, _mod1|_P4, _mod4|_P5, 0, 0, 0, _mod2|_P3},	// Module 3
{ _HO01R1, _mod5|_P4, 0, 0, 0, _mod3|_P2, _mod1|_P3},	// Module 4
{ _HO01R1, 0, 0, 0, _mod4|_P1, _mod1|_P2, _mod6|_P3},	// Module 5
{ _HO01R1, 0, 0, _mod5|_P6, _mod1|_P1, _mod7|_P2, 0},	// Module 6
{ _HO01R1, 0, _mod6|_P5, _mod1|_P6, _mod2|_P1, 0, 0}    // Module 7
};

/************************ (C) COPYRIGHT OU *****END OF FILE****/
