/**
  ******************************************************************************
  * File Name          : topology.h
  * Date               : 03-Aug-2015
  *	Author 			   : Asaad Kaadan
  * Description        : This file is automatically generated by the 'topogen' MATLAB tool.
  *
  ******************************************************************************
  */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __topology_H
#define __topology_H
#ifdef __cplusplus
 extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32f0xx_hal.h"

// Module Part Numbers:
// HO01R1: Hexagon receiver with VEMT3700 - 30mm optical resolution.
// HO01R2: Hexagon receiver with VEMT3700 - 20mm optical resolution.
// HO02R0: Hexagon transmitter  with VSMY2850G - 30mm optical resolution.
// HO02R1: Hexagon transmitter  with VSMY2850G - 20mm optical resolution.
// PO01R0: Pentagon receiver with VEMT3700 compatible with hexagons 30mm optical resolution.
// PO02R0: Pentagon transmitter  with VSMY2850G compatible with hexagons 30mm optical resolution.

// Enumerations
enum	modulePartNumbers{_HO01R1, _HO01R2, _HO02R0, _HO02R1, _PO01R0, _PO02R0};
enum	portPol{_normal, _reversed};
enum	modulePorts{_P1=1, _P2, _P3, _P4, _P5, _P6};

#define _N	127					// Number of array modules

// Array modules
#define _mod1	1<<3
#define _mod2	2<<3
#define _mod3	3<<3
#define _mod4	4<<3
#define _mod5	5<<3
#define _mod6	6<<3
#define _mod7	7<<3
#define _mod8	8<<3
#define _mod9	9<<3
#define _mod10	10<<3
#define _mod11	11<<3
#define _mod12	12<<3
#define _mod13	13<<3
#define _mod14	14<<3
#define _mod15	15<<3
#define _mod16	16<<3
#define _mod17	17<<3
#define _mod18	18<<3
#define _mod19	19<<3
#define _mod20	20<<3
#define _mod21	21<<3
#define _mod22	22<<3
#define _mod23	23<<3
#define _mod24	24<<3
#define _mod25	25<<3
#define _mod26	26<<3
#define _mod27	27<<3
#define _mod28	28<<3
#define _mod29	29<<3
#define _mod30	30<<3
#define _mod31	31<<3
#define _mod32	32<<3
#define _mod33	33<<3
#define _mod34	34<<3
#define _mod35	35<<3
#define _mod36	36<<3
#define _mod37	37<<3
#define _mod38	38<<3
#define _mod39	39<<3
#define _mod40	40<<3
#define _mod41	41<<3
#define _mod42	42<<3
#define _mod43	43<<3
#define _mod44	44<<3
#define _mod45	45<<3
#define _mod46	46<<3
#define _mod47	47<<3
#define _mod48	48<<3
#define _mod49	49<<3
#define _mod50	50<<3
#define _mod51	51<<3
#define _mod52	52<<3
#define _mod53	53<<3
#define _mod54	54<<3
#define _mod55	55<<3
#define _mod56	56<<3
#define _mod57	57<<3
#define _mod58	58<<3
#define _mod59	59<<3
#define _mod60	60<<3
#define _mod61	61<<3
#define _mod62	62<<3
#define _mod63	63<<3
#define _mod64	64<<3
#define _mod65	65<<3
#define _mod66	66<<3
#define _mod67	67<<3
#define _mod68	68<<3
#define _mod69	69<<3
#define _mod70	70<<3
#define _mod71	71<<3
#define _mod72	72<<3
#define _mod73	73<<3
#define _mod74	74<<3
#define _mod75	75<<3
#define _mod76	76<<3
#define _mod77	77<<3
#define _mod78	78<<3
#define _mod79	79<<3
#define _mod80	80<<3
#define _mod81	81<<3
#define _mod82	82<<3
#define _mod83	83<<3
#define _mod84	84<<3
#define _mod85	85<<3
#define _mod86	86<<3
#define _mod87	87<<3
#define _mod88	88<<3
#define _mod89	89<<3
#define _mod90	90<<3
#define _mod91	91<<3
#define _mod92	92<<3
#define _mod93	93<<3
#define _mod94	94<<3
#define _mod95	95<<3
#define _mod96	96<<3
#define _mod97	97<<3
#define _mod98	98<<3
#define _mod99	99<<3
#define _mod100	100<<3
#define _mod101	101<<3
#define _mod102	102<<3
#define _mod103	103<<3
#define _mod104	104<<3
#define _mod105	105<<3
#define _mod106	106<<3
#define _mod107	107<<3
#define _mod108	108<<3
#define _mod109	109<<3
#define _mod110	110<<3
#define _mod111	111<<3
#define _mod112	112<<3
#define _mod113	113<<3
#define _mod114	114<<3
#define _mod115	115<<3
#define _mod116	116<<3
#define _mod117	117<<3
#define _mod118	118<<3
#define _mod119	119<<3
#define _mod120	120<<3
#define _mod121	121<<3
#define _mod122	122<<3
#define _mod123	123<<3
#define _mod124	124<<3
#define _mod125	125<<3
#define _mod126	126<<3
#define _mod127	127<<3

// Topology
static uint16_t array[_N][7] = {
{ _HO01R1, _mod6|_P4, _mod5|_P5, _mod4|_P6, _mod3|_P1, _mod2|_P2, _mod7|_P3},	// Module 1
{ _HO01R1, _mod7|_P4, _mod1|_P5, _mod3|_P6, _mod9|_P1, _mod8|_P2, _mod19|_P3},	// Module 2
{ _HO01R1, _mod1|_P4, _mod4|_P5, _mod11|_P6, _mod10|_P1, _mod9|_P2, _mod2|_P3},	// Module 3
{ _HO01R1, _mod5|_P4, _mod13|_P5, _mod12|_P6, _mod11|_P1, _mod3|_P2, _mod1|_P3},	// Module 4
{ _HO01R1, _mod15|_P4, _mod14|_P5, _mod13|_P6, _mod4|_P1, _mod1|_P2, _mod6|_P3},	// Module 5
{ _HO01R1, _mod16|_P4, _mod15|_P5, _mod5|_P6, _mod1|_P1, _mod7|_P2, _mod17|_P3},	// Module 6
{ _HO01R1, _mod17|_P4, _mod6|_P5, _mod1|_P6, _mod2|_P1, _mod19|_P2, _mod18|_P3},	// Module 7
{ _HO01R1, _mod19|_P4, _mod2|_P5, _mod9|_P6, _mod21|_P1, _mod20|_P2, _mod37|_P3},	// Module 8
{ _HO01R1, _mod2|_P4, _mod3|_P5, _mod10|_P6, _mod22|_P1, _mod21|_P2, _mod8|_P3},	// Module 9
{ _HO01R1, _mod3|_P4, _mod11|_P5, _mod24|_P6, _mod23|_P1, _mod22|_P2, _mod9|_P3},	// Module 10
{ _HO01R1, _mod4|_P4, _mod12|_P5, _mod25|_P6, _mod24|_P1, _mod10|_P2, _mod3|_P3},	// Module 11
{ _HO01R1, _mod13|_P4, _mod27|_P5, _mod26|_P6, _mod25|_P1, _mod11|_P2, _mod4|_P3},	// Module 12
{ _HO01R1, _mod14|_P4, _mod28|_P5, _mod27|_P6, _mod12|_P1, _mod4|_P2, _mod5|_P3},	// Module 13
{ _HO01R1, _mod30|_P4, _mod29|_P5, _mod28|_P6, _mod13|_P1, _mod5|_P2, _mod15|_P3},	// Module 14
{ _HO01R1, _mod31|_P4, _mod30|_P5, _mod14|_P6, _mod5|_P1, _mod6|_P2, _mod16|_P3},	// Module 15
{ _HO01R1, _mod32|_P4, _mod31|_P5, _mod15|_P6, _mod6|_P1, _mod17|_P2, _mod33|_P3},	// Module 16
{ _HO01R1, _mod33|_P4, _mod16|_P5, _mod6|_P6, _mod7|_P1, _mod18|_P2, _mod34|_P3},	// Module 17
{ _HO01R1, _mod34|_P4, _mod17|_P5, _mod7|_P6, _mod19|_P1, _mod36|_P2, _mod35|_P3},	// Module 18
{ _HO01R1, _mod18|_P4, _mod7|_P5, _mod2|_P6, _mod8|_P1, _mod37|_P2, _mod36|_P3},	// Module 19
{ _HO01R1, _mod37|_P4, _mod8|_P5, _mod21|_P6, _mod39|_P1, _mod38|_P2, _mod61|_P3},	// Module 20
{ _HO01R1, _mod8|_P4, _mod9|_P5, _mod22|_P6, _mod40|_P1, _mod39|_P2, _mod20|_P3},	// Module 21
{ _HO01R1, _mod9|_P4, _mod10|_P5, _mod23|_P6, _mod41|_P1, _mod40|_P2, _mod21|_P3},	// Module 22
{ _HO01R1, _mod10|_P4, _mod24|_P5, _mod43|_P6, _mod42|_P1, _mod41|_P2, _mod22|_P3},	// Module 23
{ _HO01R1, _mod11|_P4, _mod25|_P5, _mod44|_P6, _mod43|_P1, _mod23|_P2, _mod10|_P3},	// Module 24
{ _HO01R1, _mod12|_P4, _mod26|_P5, _mod45|_P6, _mod44|_P1, _mod24|_P2, _mod11|_P3},	// Module 25
{ _HO01R1, _mod27|_P4, _mod47|_P5, _mod46|_P6, _mod45|_P1, _mod25|_P2, _mod12|_P3},	// Module 26
{ _HO01R1, _mod28|_P4, _mod48|_P5, _mod47|_P6, _mod26|_P1, _mod12|_P2, _mod13|_P3},	// Module 27
{ _HO01R1, _mod29|_P4, _mod49|_P5, _mod48|_P6, _mod27|_P1, _mod13|_P2, _mod14|_P3},	// Module 28
{ _HO01R1, _mod51|_P4, _mod50|_P5, _mod49|_P6, _mod28|_P1, _mod14|_P2, _mod30|_P3},	// Module 29
{ _HO01R1, _mod52|_P4, _mod51|_P5, _mod29|_P6, _mod14|_P1, _mod15|_P2, _mod31|_P3},	// Module 30
{ _HO01R1, _mod53|_P4, _mod52|_P5, _mod30|_P6, _mod15|_P1, _mod16|_P2, _mod32|_P3},	// Module 31
{ _HO01R1, _mod54|_P4, _mod53|_P5, _mod31|_P6, _mod16|_P1, _mod33|_P2, _mod55|_P3},	// Module 32
{ _HO01R1, _mod55|_P4, _mod32|_P5, _mod16|_P6, _mod17|_P1, _mod34|_P2, _mod56|_P3},	// Module 33
{ _HO01R1, _mod56|_P4, _mod33|_P5, _mod17|_P6, _mod18|_P1, _mod35|_P2, _mod57|_P3},	// Module 34
{ _HO01R1, _mod57|_P4, _mod34|_P5, _mod18|_P6, _mod36|_P1, _mod59|_P2, _mod58|_P3},	// Module 35
{ _HO01R1, _mod35|_P4, _mod18|_P5, _mod19|_P6, _mod37|_P1, _mod60|_P2, _mod59|_P3},	// Module 36
{ _HO01R1, _mod36|_P4, _mod19|_P5, _mod8|_P6, _mod20|_P1, _mod61|_P2, _mod60|_P3},	// Module 37
{ _HO01R1, _mod61|_P4, _mod20|_P5, _mod39|_P6, _mod63|_P1, _mod62|_P2, _mod91|_P3},	// Module 38
{ _HO01R1, _mod20|_P4, _mod21|_P5, _mod40|_P6, _mod64|_P1, _mod63|_P2, _mod38|_P3},	// Module 39
{ _HO01R1, _mod21|_P4, _mod22|_P5, _mod41|_P6, _mod65|_P1, _mod64|_P2, _mod39|_P3},	// Module 40
{ _HO01R1, _mod22|_P4, _mod23|_P5, _mod42|_P6, _mod66|_P1, _mod65|_P2, _mod40|_P3},	// Module 41
{ _HO01R1, _mod23|_P4, _mod43|_P5, _mod68|_P6, _mod67|_P1, _mod66|_P2, _mod41|_P3},	// Module 42
{ _HO01R1, _mod24|_P4, _mod44|_P5, _mod69|_P6, _mod68|_P1, _mod42|_P2, _mod23|_P3},	// Module 43
{ _HO01R1, _mod25|_P4, _mod45|_P5, _mod70|_P6, _mod69|_P1, _mod43|_P2, _mod24|_P3},	// Module 44
{ _HO01R1, _mod26|_P4, _mod46|_P5, _mod71|_P6, _mod70|_P1, _mod44|_P2, _mod25|_P3},	// Module 45
{ _HO01R1, _mod47|_P4, _mod73|_P5, _mod72|_P6, _mod71|_P1, _mod45|_P2, _mod26|_P3},	// Module 46
{ _HO01R1, _mod48|_P4, _mod74|_P5, _mod73|_P6, _mod46|_P1, _mod26|_P2, _mod27|_P3},	// Module 47
{ _HO01R1, _mod49|_P4, _mod75|_P5, _mod74|_P6, _mod47|_P1, _mod27|_P2, _mod28|_P3},	// Module 48
{ _HO01R1, _mod50|_P4, _mod76|_P5, _mod75|_P6, _mod48|_P1, _mod28|_P2, _mod29|_P3},	// Module 49
{ _HO01R1, _mod78|_P4, _mod77|_P5, _mod76|_P6, _mod49|_P1, _mod29|_P2, _mod51|_P3},	// Module 50
{ _HO01R1, _mod79|_P4, _mod78|_P5, _mod50|_P6, _mod29|_P1, _mod30|_P2, _mod52|_P3},	// Module 51
{ _HO01R1, _mod80|_P4, _mod79|_P5, _mod51|_P6, _mod30|_P1, _mod31|_P2, _mod53|_P3},	// Module 52
{ _HO01R1, _mod81|_P4, _mod80|_P5, _mod52|_P6, _mod31|_P1, _mod32|_P2, _mod54|_P3},	// Module 53
{ _HO01R1, _mod82|_P4, _mod81|_P5, _mod53|_P6, _mod32|_P1, _mod55|_P2, _mod83|_P3},	// Module 54
{ _HO01R1, _mod83|_P4, _mod54|_P5, _mod32|_P6, _mod33|_P1, _mod56|_P2, _mod84|_P3},	// Module 55
{ _HO01R1, _mod84|_P4, _mod55|_P5, _mod33|_P6, _mod34|_P1, _mod57|_P2, _mod85|_P3},	// Module 56
{ _HO01R1, _mod85|_P4, _mod56|_P5, _mod34|_P6, _mod35|_P1, _mod58|_P2, _mod86|_P3},	// Module 57
{ _HO01R1, _mod86|_P4, _mod57|_P5, _mod35|_P6, _mod59|_P1, _mod88|_P2, _mod87|_P3},	// Module 58
{ _HO01R1, _mod58|_P4, _mod35|_P5, _mod36|_P6, _mod60|_P1, _mod89|_P2, _mod88|_P3},	// Module 59
{ _HO01R1, _mod59|_P4, _mod36|_P5, _mod37|_P6, _mod61|_P1, _mod90|_P2, _mod89|_P3},	// Module 60
{ _HO01R1, _mod60|_P4, _mod37|_P5, _mod20|_P6, _mod38|_P1, _mod91|_P2, _mod90|_P3},	// Module 61
{ _HO01R1, _mod91|_P4, _mod38|_P5, _mod63|_P6, _mod93|_P1, _mod92|_P2, _mod127|_P3},	// Module 62
{ _HO01R1, _mod38|_P4, _mod39|_P5, _mod64|_P6, _mod94|_P1, _mod93|_P2, _mod62|_P3},	// Module 63
{ _HO01R1, _mod39|_P4, _mod40|_P5, _mod65|_P6, _mod95|_P1, _mod94|_P2, _mod63|_P3},	// Module 64
{ _HO01R1, _mod40|_P4, _mod41|_P5, _mod66|_P6, _mod96|_P1, _mod95|_P2, _mod64|_P3},	// Module 65
{ _HO01R1, _mod41|_P4, _mod42|_P5, _mod67|_P6, _mod97|_P1, _mod96|_P2, _mod65|_P3},	// Module 66
{ _HO01R1, _mod42|_P4, _mod68|_P5, _mod99|_P6, _mod98|_P1, _mod97|_P2, _mod66|_P3},	// Module 67
{ _HO01R1, _mod43|_P4, _mod69|_P5, _mod100|_P6, _mod99|_P1, _mod67|_P2, _mod42|_P3},	// Module 68
{ _HO01R1, _mod44|_P4, _mod70|_P5, _mod101|_P6, _mod100|_P1, _mod68|_P2, _mod43|_P3},	// Module 69
{ _HO01R1, _mod45|_P4, _mod71|_P5, _mod102|_P6, _mod101|_P1, _mod69|_P2, _mod44|_P3},	// Module 70
{ _HO01R1, _mod46|_P4, _mod72|_P5, _mod103|_P6, _mod102|_P1, _mod70|_P2, _mod45|_P3},	// Module 71
{ _HO01R1, _mod73|_P4, _mod105|_P5, _mod104|_P6, _mod103|_P1, _mod71|_P2, _mod46|_P3},	// Module 72
{ _HO01R1, _mod74|_P4, _mod106|_P5, _mod105|_P6, _mod72|_P1, _mod46|_P2, _mod47|_P3},	// Module 73
{ _HO01R1, _mod75|_P4, _mod107|_P5, _mod106|_P6, _mod73|_P1, _mod47|_P2, _mod48|_P3},	// Module 74
{ _HO01R1, _mod76|_P4, _mod108|_P5, _mod107|_P6, _mod74|_P1, _mod48|_P2, _mod49|_P3},	// Module 75
{ _HO01R1, _mod77|_P4, _mod109|_P5, _mod108|_P6, _mod75|_P1, _mod49|_P2, _mod50|_P3},	// Module 76
{ _HO01R1, _mod111|_P4, _mod110|_P5, _mod109|_P6, _mod76|_P1, _mod50|_P2, _mod78|_P3},	// Module 77
{ _HO01R1, _mod112|_P4, _mod111|_P5, _mod77|_P6, _mod50|_P1, _mod51|_P2, _mod79|_P3},	// Module 78
{ _HO01R1, _mod113|_P4, _mod112|_P5, _mod78|_P6, _mod51|_P1, _mod52|_P2, _mod80|_P3},	// Module 79
{ _HO01R1, _mod114|_P4, _mod113|_P5, _mod79|_P6, _mod52|_P1, _mod53|_P2, _mod81|_P3},	// Module 80
{ _HO01R1, _mod115|_P4, _mod114|_P5, _mod80|_P6, _mod53|_P1, _mod54|_P2, _mod82|_P3},	// Module 81
{ _HO01R1, _mod116|_P4, _mod115|_P5, _mod81|_P6, _mod54|_P1, _mod83|_P2, _mod117|_P3},	// Module 82
{ _HO01R1, _mod117|_P4, _mod82|_P5, _mod54|_P6, _mod55|_P1, _mod84|_P2, _mod118|_P3},	// Module 83
{ _HO01R1, _mod118|_P4, _mod83|_P5, _mod55|_P6, _mod56|_P1, _mod85|_P2, _mod119|_P3},	// Module 84
{ _HO01R1, _mod119|_P4, _mod84|_P5, _mod56|_P6, _mod57|_P1, _mod86|_P2, _mod120|_P3},	// Module 85
{ _HO01R1, _mod120|_P4, _mod85|_P5, _mod57|_P6, _mod58|_P1, _mod87|_P2, _mod121|_P3},	// Module 86
{ _HO01R1, _mod121|_P4, _mod86|_P5, _mod58|_P6, _mod88|_P1, _mod123|_P2, _mod122|_P3},	// Module 87
{ _HO01R1, _mod87|_P4, _mod58|_P5, _mod59|_P6, _mod89|_P1, _mod124|_P2, _mod123|_P3},	// Module 88
{ _HO01R1, _mod88|_P4, _mod59|_P5, _mod60|_P6, _mod90|_P1, _mod125|_P2, _mod124|_P3},	// Module 89
{ _HO01R1, _mod89|_P4, _mod60|_P5, _mod61|_P6, _mod91|_P1, _mod126|_P2, _mod125|_P3},	// Module 90
{ _HO01R1, _mod90|_P4, _mod61|_P5, _mod38|_P6, _mod62|_P1, _mod127|_P2, _mod126|_P3},	// Module 91
{ _HO01R1, _mod127|_P4, _mod62|_P5, _mod93|_P6, 0, 0, 0},	// Module 92
{ _HO01R1, _mod62|_P4, _mod63|_P5, _mod94|_P6, 0, 0, _mod92|_P3},	// Module 93
{ _HO01R1, _mod63|_P4, _mod64|_P5, _mod95|_P6, 0, 0, _mod93|_P3},	// Module 94
{ _HO01R1, _mod64|_P4, _mod65|_P5, _mod96|_P6, 0, 0, _mod94|_P3},	// Module 95
{ _HO01R1, _mod65|_P4, _mod66|_P5, _mod97|_P6, 0, 0, _mod95|_P3},	// Module 96
{ _HO01R1, _mod66|_P4, _mod67|_P5, _mod98|_P6, 0, 0, _mod96|_P3},	// Module 97
{ _HO01R1, _mod67|_P4, _mod99|_P5, 0, 0, 0, _mod97|_P3},	// Module 98
{ _HO01R1, _mod68|_P4, _mod100|_P5, 0, 0, _mod98|_P2, _mod67|_P3},	// Module 99
{ _HO01R1, _mod69|_P4, _mod101|_P5, 0, 0, _mod99|_P2, _mod68|_P3},	// Module 100
{ _HO01R1, _mod70|_P4, _mod102|_P5, 0, 0, _mod100|_P2, _mod69|_P3},	// Module 101
{ _HO01R1, _mod71|_P4, _mod103|_P5, 0, 0, _mod101|_P2, _mod70|_P3},	// Module 102
{ _HO01R1, _mod72|_P4, _mod104|_P5, 0, 0, _mod102|_P2, _mod71|_P3},	// Module 103
{ _HO01R1, _mod105|_P4, 0, 0, 0, _mod103|_P2, _mod72|_P3},	// Module 104
{ _HO01R1, _mod106|_P4, 0, 0, _mod104|_P1, _mod72|_P2, _mod73|_P3},	// Module 105
{ _HO01R1, _mod107|_P4, 0, 0, _mod105|_P1, _mod73|_P2, _mod74|_P3},	// Module 106
{ _HO01R1, _mod108|_P4, 0, 0, _mod106|_P1, _mod74|_P2, _mod75|_P3},	// Module 107
{ _HO01R1, _mod109|_P4, 0, 0, _mod107|_P1, _mod75|_P2, _mod76|_P3},	// Module 108
{ _HO01R1, _mod110|_P4, 0, 0, _mod108|_P1, _mod76|_P2, _mod77|_P3},	// Module 109
{ _HO01R1, 0, 0, 0, _mod109|_P1, _mod77|_P2, _mod111|_P3},	// Module 110
{ _HO01R1, 0, 0, _mod110|_P6, _mod77|_P1, _mod78|_P2, _mod112|_P3},	// Module 111
{ _HO01R1, 0, 0, _mod111|_P6, _mod78|_P1, _mod79|_P2, _mod113|_P3},	// Module 112
{ _HO01R1, 0, 0, _mod112|_P6, _mod79|_P1, _mod80|_P2, _mod114|_P3},	// Module 113
{ _HO01R1, 0, 0, _mod113|_P6, _mod80|_P1, _mod81|_P2, _mod115|_P3},	// Module 114
{ _HO01R1, 0, 0, _mod114|_P6, _mod81|_P1, _mod82|_P2, _mod116|_P3},	// Module 115
{ _HO01R1, 0, 0, _mod115|_P6, _mod82|_P1, _mod117|_P2, 0},	// Module 116
{ _HO01R1, 0, _mod116|_P5, _mod82|_P6, _mod83|_P1, _mod118|_P2, 0},	// Module 117
{ _HO01R1, 0, _mod117|_P5, _mod83|_P6, _mod84|_P1, _mod119|_P2, 0},	// Module 118
{ _HO01R1, 0, _mod118|_P5, _mod84|_P6, _mod85|_P1, _mod120|_P2, 0},	// Module 119
{ _HO01R1, 0, _mod119|_P5, _mod85|_P6, _mod86|_P1, _mod121|_P2, 0},	// Module 120
{ _HO01R1, 0, _mod120|_P5, _mod86|_P6, _mod87|_P1, _mod122|_P2, 0},	// Module 121
{ _HO01R1, 0, _mod121|_P5, _mod87|_P6, _mod123|_P1, 0, 0},	// Module 122
{ _HO01R1, _mod122|_P4, _mod87|_P5, _mod88|_P6, _mod124|_P1, 0, 0},	// Module 123
{ _HO01R1, _mod123|_P4, _mod88|_P5, _mod89|_P6, _mod125|_P1, 0, 0},	// Module 124
{ _HO01R1, _mod124|_P4, _mod89|_P5, _mod90|_P6, _mod126|_P1, 0, 0},	// Module 125
{ _HO01R1, _mod125|_P4, _mod90|_P5, _mod91|_P6, _mod127|_P1, 0, 0},	// Module 126
{ _HO01R1, _mod126|_P4, _mod91|_P5, _mod62|_P6, _mod92|_P1, 0, 0}    // Module 127
};

// Configurations for duplex serial ports
#ifdef _module_1
	#define	_module	1
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_2
	#define	_module	2
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_3
	#define	_module	3
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_4
	#define	_module	4
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_5
	#define	_module	5
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_6
	#define	_module	6
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_7
	#define	_module	7
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_8
	#define	_module	8
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_9
	#define	_module	9
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_10
	#define	_module	10
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_11
	#define	_module	11
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_12
	#define	_module	12
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_13
	#define	_module	13
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_14
	#define	_module	14
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_15
	#define	_module	15
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_16
	#define	_module	16
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_17
	#define	_module	17
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_18
	#define	_module	18
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_19
	#define	_module	19
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_20
	#define	_module	20
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_21
	#define	_module	21
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_22
	#define	_module	22
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_23
	#define	_module	23
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_24
	#define	_module	24
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_25
	#define	_module	25
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_26
	#define	_module	26
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_27
	#define	_module	27
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_28
	#define	_module	28
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_29
	#define	_module	29
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_30
	#define	_module	30
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_31
	#define	_module	31
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_32
	#define	_module	32
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_33
	#define	_module	33
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_34
	#define	_module	34
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_35
	#define	_module	35
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_36
	#define	_module	36
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_37
	#define	_module	37
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_38
	#define	_module	38
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_39
	#define	_module	39
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_40
	#define	_module	40
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_41
	#define	_module	41
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_42
	#define	_module	42
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_43
	#define	_module	43
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_44
	#define	_module	44
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_45
	#define	_module	45
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_46
	#define	_module	46
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_47
	#define	_module	47
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_48
	#define	_module	48
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_49
	#define	_module	49
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_50
	#define	_module	50
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_51
	#define	_module	51
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_52
	#define	_module	52
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_53
	#define	_module	53
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_54
	#define	_module	54
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_55
	#define	_module	55
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_56
	#define	_module	56
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_57
	#define	_module	57
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_58
	#define	_module	58
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_59
	#define	_module	59
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_60
	#define	_module	60
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_61
	#define	_module	61
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_62
	#define	_module	62
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_63
	#define	_module	63
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_64
	#define	_module	64
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_65
	#define	_module	65
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_66
	#define	_module	66
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_67
	#define	_module	67
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_68
	#define	_module	68
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_69
	#define	_module	69
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_70
	#define	_module	70
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_71
	#define	_module	71
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_72
	#define	_module	72
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_73
	#define	_module	73
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_74
	#define	_module	74
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_75
	#define	_module	75
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_76
	#define	_module	76
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_77
	#define	_module	77
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_78
	#define	_module	78
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_79
	#define	_module	79
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_80
	#define	_module	80
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_81
	#define	_module	81
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_82
	#define	_module	82
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_83
	#define	_module	83
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_84
	#define	_module	84
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_85
	#define	_module	85
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_86
	#define	_module	86
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_87
	#define	_module	87
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_88
	#define	_module	88
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_89
	#define	_module	89
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_90
	#define	_module	90
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_91
	#define	_module	91
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_92
	#define	_module	92
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_93
	#define	_module	93
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_94
	#define	_module	94
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_95
	#define	_module	95
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_96
	#define	_module	96
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_97
	#define	_module	97
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_reversed	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_98
	#define	_module	98
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_99
	#define	_module	99
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_100
	#define	_module	100
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_101
	#define	_module	101
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_102
	#define	_module	102
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_103
	#define	_module	103
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_reversed	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_104
	#define	_module	104
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_105
	#define	_module	105
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_106
	#define	_module	106
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_107
	#define	_module	107
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_108
	#define	_module	108
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_109
	#define	_module	109
	#define	HO01R1	1
	#define	_P1pol_reversed	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_110
	#define	_module	110
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_111
	#define	_module	111
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_112
	#define	_module	112
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_113
	#define	_module	113
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_114
	#define	_module	114
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_115
	#define	_module	115
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_reversed	1
#endif
#ifdef _module_116
	#define	_module	116
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_117
	#define	_module	117
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_118
	#define	_module	118
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_119
	#define	_module	119
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_120
	#define	_module	120
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_121
	#define	_module	121
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_reversed	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_122
	#define	_module	122
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_123
	#define	_module	123
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_124
	#define	_module	124
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_125
	#define	_module	125
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_126
	#define	_module	126
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_reversed	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif
#ifdef _module_127
	#define	_module	127
	#define	HO01R1	1
	#define	_P1pol_normal	1
	#define	_P2pol_normal	1
	#define	_P3pol_normal	1
	#define	_P4pol_normal	1
	#define	_P5pol_normal	1
	#define	_P6pol_normal	1
#endif


#ifdef __cplusplus
}
#endif
#endif /*__topology_H */
/**
  * @}
  */

/**
  * @}
  */

/************************ (C) COPYRIGHT OU *****END OF FILE****/
