/**
  ******************************************************************************
  * File Name          : topology.h
  * Date               : 12-Aug-2015
  *	Author 			   : Asaad Kaadan
  * Description        : This file is automatically generated by the 'topogen' MATLAB tool.
  *                      This version is compiled for MOWE-Tandy simulator use.
  *
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include <stdint.h>

// Module Part Numbers:
// HO01R1: Hexagon receiver with VEMT3700 - 30mm optical resolution.
// HO01R2: Hexagon receiver with VEMT3700 - 20mm optical resolution.
// HO02R0: Hexagon transmitter  with VSMY2850G - 30mm optical resolution.
// HO02R1: Hexagon transmitter  with VSMY2850G - 20mm optical resolution.
// PO01R0: Pentagon receiver with VEMT3700 compatible with hexagons 30mm optical resolution.
// PO02R0: Pentagon transmitter  with VSMY2850G compatible with hexagons 30mm optical resolution.

// Enumerations
enum	modulePartNumbers{_HO01R1, _HO01R2, _HO02R0, _HO02R1, _PO01R0, _PO02R0};
enum	portPol{_normal, _reversed};
enum	modulePorts{_P1=1, _P2, _P3, _P4, _P5, _P6};

#define _N	37					// Number of array modules

#define portCount	6

// Array modules
#define _mod1	1<<8
#define _mod2	2<<8
#define _mod3	3<<8
#define _mod4	4<<8
#define _mod5	5<<8
#define _mod6	6<<8
#define _mod7	7<<8
#define _mod8	8<<8
#define _mod9	9<<8
#define _mod10	10<<8
#define _mod11	11<<8
#define _mod12	12<<8
#define _mod13	13<<8
#define _mod14	14<<8
#define _mod15	15<<8
#define _mod16	16<<8
#define _mod17	17<<8
#define _mod18	18<<8
#define _mod19	19<<8
#define _mod20	20<<8
#define _mod21	21<<8
#define _mod22	22<<8
#define _mod23	23<<8
#define _mod24	24<<8
#define _mod25	25<<8
#define _mod26	26<<8
#define _mod27	27<<8
#define _mod28	28<<8
#define _mod29	29<<8
#define _mod30	30<<8
#define _mod31	31<<8
#define _mod32	32<<8
#define _mod33	33<<8
#define _mod34	34<<8
#define _mod35	35<<8
#define _mod36	36<<8
#define _mod37	37<<8

// Topology
static uint16_t array[_N][7] = {
{ _HO01R1, _mod6|_P4, _mod5|_P5, _mod4|_P6, _mod3|_P1, _mod2|_P2, _mod7|_P3},	// Module 1
{ _HO01R1, _mod7|_P4, _mod1|_P5, _mod3|_P6, _mod9|_P1, _mod8|_P2, _mod19|_P3},	// Module 2
{ _HO01R1, _mod1|_P4, _mod4|_P5, _mod11|_P6, _mod10|_P1, _mod9|_P2, _mod2|_P3},	// Module 3
{ _HO01R1, _mod5|_P4, _mod13|_P5, _mod12|_P6, _mod11|_P1, _mod3|_P2, _mod1|_P3},	// Module 4
{ _HO01R1, _mod15|_P4, _mod14|_P5, _mod13|_P6, _mod4|_P1, _mod1|_P2, _mod6|_P3},	// Module 5
{ _HO01R1, _mod16|_P4, _mod15|_P5, _mod5|_P6, _mod1|_P1, _mod7|_P2, _mod17|_P3},	// Module 6
{ _HO01R1, _mod17|_P4, _mod6|_P5, _mod1|_P6, _mod2|_P1, _mod19|_P2, _mod18|_P3},	// Module 7
{ _HO01R1, _mod19|_P4, _mod2|_P5, _mod9|_P6, _mod21|_P1, _mod20|_P2, _mod37|_P3},	// Module 8
{ _HO01R1, _mod2|_P4, _mod3|_P5, _mod10|_P6, _mod22|_P1, _mod21|_P2, _mod8|_P3},	// Module 9
{ _HO01R1, _mod3|_P4, _mod11|_P5, _mod24|_P6, _mod23|_P1, _mod22|_P2, _mod9|_P3},	// Module 10
{ _HO01R1, _mod4|_P4, _mod12|_P5, _mod25|_P6, _mod24|_P1, _mod10|_P2, _mod3|_P3},	// Module 11
{ _HO01R1, _mod13|_P4, _mod27|_P5, _mod26|_P6, _mod25|_P1, _mod11|_P2, _mod4|_P3},	// Module 12
{ _HO01R1, _mod14|_P4, _mod28|_P5, _mod27|_P6, _mod12|_P1, _mod4|_P2, _mod5|_P3},	// Module 13
{ _HO01R1, _mod30|_P4, _mod29|_P5, _mod28|_P6, _mod13|_P1, _mod5|_P2, _mod15|_P3},	// Module 14
{ _HO01R1, _mod31|_P4, _mod30|_P5, _mod14|_P6, _mod5|_P1, _mod6|_P2, _mod16|_P3},	// Module 15
{ _HO01R1, _mod32|_P4, _mod31|_P5, _mod15|_P6, _mod6|_P1, _mod17|_P2, _mod33|_P3},	// Module 16
{ _HO01R1, _mod33|_P4, _mod16|_P5, _mod6|_P6, _mod7|_P1, _mod18|_P2, _mod34|_P3},	// Module 17
{ _HO01R1, _mod34|_P4, _mod17|_P5, _mod7|_P6, _mod19|_P1, _mod36|_P2, _mod35|_P3},	// Module 18
{ _HO01R1, _mod18|_P4, _mod7|_P5, _mod2|_P6, _mod8|_P1, _mod37|_P2, _mod36|_P3},	// Module 19
{ _HO01R1, _mod37|_P4, _mod8|_P5, _mod21|_P6, 0, 0, 0},	// Module 20
{ _HO01R1, _mod8|_P4, _mod9|_P5, _mod22|_P6, 0, 0, _mod20|_P3},	// Module 21
{ _HO01R1, _mod9|_P4, _mod10|_P5, _mod23|_P6, 0, 0, _mod21|_P3},	// Module 22
{ _HO01R1, _mod10|_P4, _mod24|_P5, 0, 0, 0, _mod22|_P3},	// Module 23
{ _HO01R1, _mod11|_P4, _mod25|_P5, 0, 0, _mod23|_P2, _mod10|_P3},	// Module 24
{ _HO01R1, _mod12|_P4, _mod26|_P5, 0, 0, _mod24|_P2, _mod11|_P3},	// Module 25
{ _HO01R1, _mod27|_P4, 0, 0, 0, _mod25|_P2, _mod12|_P3},	// Module 26
{ _HO01R1, _mod28|_P4, 0, 0, _mod26|_P1, _mod12|_P2, _mod13|_P3},	// Module 27
{ _HO01R1, _mod29|_P4, 0, 0, _mod27|_P1, _mod13|_P2, _mod14|_P3},	// Module 28
{ _HO01R1, 0, 0, 0, _mod28|_P1, _mod14|_P2, _mod30|_P3},	// Module 29
{ _HO01R1, 0, 0, _mod29|_P6, _mod14|_P1, _mod15|_P2, _mod31|_P3},	// Module 30
{ _HO01R1, 0, 0, _mod30|_P6, _mod15|_P1, _mod16|_P2, _mod32|_P3},	// Module 31
{ _HO01R1, 0, 0, _mod31|_P6, _mod16|_P1, _mod33|_P2, 0},	// Module 32
{ _HO01R1, 0, _mod32|_P5, _mod16|_P6, _mod17|_P1, _mod34|_P2, 0},	// Module 33
{ _HO01R1, 0, _mod33|_P5, _mod17|_P6, _mod18|_P1, _mod35|_P2, 0},	// Module 34
{ _HO01R1, 0, _mod34|_P5, _mod18|_P6, _mod36|_P1, 0, 0},	// Module 35
{ _HO01R1, _mod35|_P4, _mod18|_P5, _mod19|_P6, _mod37|_P1, 0, 0},	// Module 36
{ _HO01R1, _mod36|_P4, _mod19|_P5, _mod8|_P6, _mod20|_P1, 0, 0}    // Module 37
};

/************************ (C) COPYRIGHT OU *****END OF FILE****/
