/**
  ******************************************************************************
  * File Name          : topo_sim.h
  * Date               : 11-Aug-2015
  *	Author 			   : Asaad Kaadan
  * Description        : This file is automatically generated by the 'topogen' MATLAB tool.
  *                      This version is compiled for MOWE-Tandy simulator use.
  *
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include <stdint.h>

// Module Part Numbers:
// HO01R1: Hexagon receiver with VEMT3700 - 30mm optical resolution.
// HO01R2: Hexagon receiver with VEMT3700 - 20mm optical resolution.
// HO02R0: Hexagon transmitter  with VSMY2850G - 30mm optical resolution.
// HO02R1: Hexagon transmitter  with VSMY2850G - 20mm optical resolution.
// PO01R0: Pentagon receiver with VEMT3700 compatible with hexagons 30mm optical resolution.
// PO02R0: Pentagon transmitter  with VSMY2850G compatible with hexagons 30mm optical resolution.

// Enumerations
enum	modulePartNumbers{_HO01R1, _HO01R2, _HO02R0, _HO02R1, _PO01R0, _PO02R0};
enum	portPol{_normal, _reversed};
enum	modulePorts{_P1=1, _P2, _P3, _P4, _P5, _P6};

#define _N	3					// Number of array modules

#define portCount	6

// Array modules
#define _mod1	1<<8
#define _mod2	2<<8
#define _mod3	3<<8

// Topology
static uint16_t array[_N][7] = {
{ _HO02R0, 0, 0, _mod3|_P4, _mod2|_P3, 0, 0},	// Module 1
{ _HO02R0, 0, 0, _mod1|_P4, _mod3|_P3, 0, 0},	// Module 2
{ _HO01R1, 0, 0, _mod2|_P4, _mod1|_P3, 0, 0}    // Module 3
};

/************************ (C) COPYRIGHT OU *****END OF FILE****/
