/**
  ******************************************************************************
  * File Name          : topology.h
  * Date               : 12-Aug-2015
  *	Author 			   : Asaad Kaadan
  * Description        : This file is automatically generated by the 'topogen' MATLAB tool.
  *                      This version is compiled for MOWE-Tandy simulator use.
  *
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include <stdint.h>

// Module Part Numbers:
// HO01R1: Hexagon receiver with VEMT3700 - 30mm optical resolution.
// HO01R2: Hexagon receiver with VEMT3700 - 20mm optical resolution.
// HO02R0: Hexagon transmitter  with VSMY2850G - 30mm optical resolution.
// HO02R1: Hexagon transmitter  with VSMY2850G - 20mm optical resolution.
// PO01R0: Pentagon receiver with VEMT3700 compatible with hexagons 30mm optical resolution.
// PO02R0: Pentagon transmitter  with VSMY2850G compatible with hexagons 30mm optical resolution.

// Enumerations
enum	modulePartNumbers{_HO01R1, _HO01R2, _HO02R0, _HO02R1, _PO01R0, _PO02R0};
enum	portPol{_normal, _reversed};
enum	modulePorts{_P1=1, _P2, _P3, _P4, _P5, _P6};

#define _N	127					// Number of array modules

#define portCount	6

// Array modules
#define _mod1	1<<8
#define _mod2	2<<8
#define _mod3	3<<8
#define _mod4	4<<8
#define _mod5	5<<8
#define _mod6	6<<8
#define _mod7	7<<8
#define _mod8	8<<8
#define _mod9	9<<8
#define _mod10	10<<8
#define _mod11	11<<8
#define _mod12	12<<8
#define _mod13	13<<8
#define _mod14	14<<8
#define _mod15	15<<8
#define _mod16	16<<8
#define _mod17	17<<8
#define _mod18	18<<8
#define _mod19	19<<8
#define _mod20	20<<8
#define _mod21	21<<8
#define _mod22	22<<8
#define _mod23	23<<8
#define _mod24	24<<8
#define _mod25	25<<8
#define _mod26	26<<8
#define _mod27	27<<8
#define _mod28	28<<8
#define _mod29	29<<8
#define _mod30	30<<8
#define _mod31	31<<8
#define _mod32	32<<8
#define _mod33	33<<8
#define _mod34	34<<8
#define _mod35	35<<8
#define _mod36	36<<8
#define _mod37	37<<8
#define _mod38	38<<8
#define _mod39	39<<8
#define _mod40	40<<8
#define _mod41	41<<8
#define _mod42	42<<8
#define _mod43	43<<8
#define _mod44	44<<8
#define _mod45	45<<8
#define _mod46	46<<8
#define _mod47	47<<8
#define _mod48	48<<8
#define _mod49	49<<8
#define _mod50	50<<8
#define _mod51	51<<8
#define _mod52	52<<8
#define _mod53	53<<8
#define _mod54	54<<8
#define _mod55	55<<8
#define _mod56	56<<8
#define _mod57	57<<8
#define _mod58	58<<8
#define _mod59	59<<8
#define _mod60	60<<8
#define _mod61	61<<8
#define _mod62	62<<8
#define _mod63	63<<8
#define _mod64	64<<8
#define _mod65	65<<8
#define _mod66	66<<8
#define _mod67	67<<8
#define _mod68	68<<8
#define _mod69	69<<8
#define _mod70	70<<8
#define _mod71	71<<8
#define _mod72	72<<8
#define _mod73	73<<8
#define _mod74	74<<8
#define _mod75	75<<8
#define _mod76	76<<8
#define _mod77	77<<8
#define _mod78	78<<8
#define _mod79	79<<8
#define _mod80	80<<8
#define _mod81	81<<8
#define _mod82	82<<8
#define _mod83	83<<8
#define _mod84	84<<8
#define _mod85	85<<8
#define _mod86	86<<8
#define _mod87	87<<8
#define _mod88	88<<8
#define _mod89	89<<8
#define _mod90	90<<8
#define _mod91	91<<8
#define _mod92	92<<8
#define _mod93	93<<8
#define _mod94	94<<8
#define _mod95	95<<8
#define _mod96	96<<8
#define _mod97	97<<8
#define _mod98	98<<8
#define _mod99	99<<8
#define _mod100	100<<8
#define _mod101	101<<8
#define _mod102	102<<8
#define _mod103	103<<8
#define _mod104	104<<8
#define _mod105	105<<8
#define _mod106	106<<8
#define _mod107	107<<8
#define _mod108	108<<8
#define _mod109	109<<8
#define _mod110	110<<8
#define _mod111	111<<8
#define _mod112	112<<8
#define _mod113	113<<8
#define _mod114	114<<8
#define _mod115	115<<8
#define _mod116	116<<8
#define _mod117	117<<8
#define _mod118	118<<8
#define _mod119	119<<8
#define _mod120	120<<8
#define _mod121	121<<8
#define _mod122	122<<8
#define _mod123	123<<8
#define _mod124	124<<8
#define _mod125	125<<8
#define _mod126	126<<8
#define _mod127	127<<8

// Topology
static uint16_t array[_N][7] = {
{ _HO01R1, _mod6|_P4, _mod5|_P5, _mod4|_P6, _mod3|_P1, _mod2|_P2, _mod7|_P3},	// Module 1
{ _HO01R1, _mod7|_P4, _mod1|_P5, _mod3|_P6, _mod9|_P1, _mod8|_P2, _mod19|_P3},	// Module 2
{ _HO01R1, _mod1|_P4, _mod4|_P5, _mod11|_P6, _mod10|_P1, _mod9|_P2, _mod2|_P3},	// Module 3
{ _HO01R1, _mod5|_P4, _mod13|_P5, _mod12|_P6, _mod11|_P1, _mod3|_P2, _mod1|_P3},	// Module 4
{ _HO01R1, _mod15|_P4, _mod14|_P5, _mod13|_P6, _mod4|_P1, _mod1|_P2, _mod6|_P3},	// Module 5
{ _HO01R1, _mod16|_P4, _mod15|_P5, _mod5|_P6, _mod1|_P1, _mod7|_P2, _mod17|_P3},	// Module 6
{ _HO01R1, _mod17|_P4, _mod6|_P5, _mod1|_P6, _mod2|_P1, _mod19|_P2, _mod18|_P3},	// Module 7
{ _HO01R1, _mod19|_P4, _mod2|_P5, _mod9|_P6, _mod21|_P1, _mod20|_P2, _mod37|_P3},	// Module 8
{ _HO01R1, _mod2|_P4, _mod3|_P5, _mod10|_P6, _mod22|_P1, _mod21|_P2, _mod8|_P3},	// Module 9
{ _HO01R1, _mod3|_P4, _mod11|_P5, _mod24|_P6, _mod23|_P1, _mod22|_P2, _mod9|_P3},	// Module 10
{ _HO01R1, _mod4|_P4, _mod12|_P5, _mod25|_P6, _mod24|_P1, _mod10|_P2, _mod3|_P3},	// Module 11
{ _HO01R1, _mod13|_P4, _mod27|_P5, _mod26|_P6, _mod25|_P1, _mod11|_P2, _mod4|_P3},	// Module 12
{ _HO01R1, _mod14|_P4, _mod28|_P5, _mod27|_P6, _mod12|_P1, _mod4|_P2, _mod5|_P3},	// Module 13
{ _HO01R1, _mod30|_P4, _mod29|_P5, _mod28|_P6, _mod13|_P1, _mod5|_P2, _mod15|_P3},	// Module 14
{ _HO01R1, _mod31|_P4, _mod30|_P5, _mod14|_P6, _mod5|_P1, _mod6|_P2, _mod16|_P3},	// Module 15
{ _HO01R1, _mod32|_P4, _mod31|_P5, _mod15|_P6, _mod6|_P1, _mod17|_P2, _mod33|_P3},	// Module 16
{ _HO01R1, _mod33|_P4, _mod16|_P5, _mod6|_P6, _mod7|_P1, _mod18|_P2, _mod34|_P3},	// Module 17
{ _HO01R1, _mod34|_P4, _mod17|_P5, _mod7|_P6, _mod19|_P1, _mod36|_P2, _mod35|_P3},	// Module 18
{ _HO01R1, _mod18|_P4, _mod7|_P5, _mod2|_P6, _mod8|_P1, _mod37|_P2, _mod36|_P3},	// Module 19
{ _HO01R1, _mod37|_P4, _mod8|_P5, _mod21|_P6, _mod39|_P1, _mod38|_P2, _mod61|_P3},	// Module 20
{ _HO01R1, _mod8|_P4, _mod9|_P5, _mod22|_P6, _mod40|_P1, _mod39|_P2, _mod20|_P3},	// Module 21
{ _HO01R1, _mod9|_P4, _mod10|_P5, _mod23|_P6, _mod41|_P1, _mod40|_P2, _mod21|_P3},	// Module 22
{ _HO01R1, _mod10|_P4, _mod24|_P5, _mod43|_P6, _mod42|_P1, _mod41|_P2, _mod22|_P3},	// Module 23
{ _HO01R1, _mod11|_P4, _mod25|_P5, _mod44|_P6, _mod43|_P1, _mod23|_P2, _mod10|_P3},	// Module 24
{ _HO01R1, _mod12|_P4, _mod26|_P5, _mod45|_P6, _mod44|_P1, _mod24|_P2, _mod11|_P3},	// Module 25
{ _HO01R1, _mod27|_P4, _mod47|_P5, _mod46|_P6, _mod45|_P1, _mod25|_P2, _mod12|_P3},	// Module 26
{ _HO01R1, _mod28|_P4, _mod48|_P5, _mod47|_P6, _mod26|_P1, _mod12|_P2, _mod13|_P3},	// Module 27
{ _HO01R1, _mod29|_P4, _mod49|_P5, _mod48|_P6, _mod27|_P1, _mod13|_P2, _mod14|_P3},	// Module 28
{ _HO01R1, _mod51|_P4, _mod50|_P5, _mod49|_P6, _mod28|_P1, _mod14|_P2, _mod30|_P3},	// Module 29
{ _HO01R1, _mod52|_P4, _mod51|_P5, _mod29|_P6, _mod14|_P1, _mod15|_P2, _mod31|_P3},	// Module 30
{ _HO01R1, _mod53|_P4, _mod52|_P5, _mod30|_P6, _mod15|_P1, _mod16|_P2, _mod32|_P3},	// Module 31
{ _HO01R1, _mod54|_P4, _mod53|_P5, _mod31|_P6, _mod16|_P1, _mod33|_P2, _mod55|_P3},	// Module 32
{ _HO01R1, _mod55|_P4, _mod32|_P5, _mod16|_P6, _mod17|_P1, _mod34|_P2, _mod56|_P3},	// Module 33
{ _HO01R1, _mod56|_P4, _mod33|_P5, _mod17|_P6, _mod18|_P1, _mod35|_P2, _mod57|_P3},	// Module 34
{ _HO01R1, _mod57|_P4, _mod34|_P5, _mod18|_P6, _mod36|_P1, _mod59|_P2, _mod58|_P3},	// Module 35
{ _HO01R1, _mod35|_P4, _mod18|_P5, _mod19|_P6, _mod37|_P1, _mod60|_P2, _mod59|_P3},	// Module 36
{ _HO01R1, _mod36|_P4, _mod19|_P5, _mod8|_P6, _mod20|_P1, _mod61|_P2, _mod60|_P3},	// Module 37
{ _HO01R1, _mod61|_P4, _mod20|_P5, _mod39|_P6, _mod63|_P1, _mod62|_P2, _mod91|_P3},	// Module 38
{ _HO01R1, _mod20|_P4, _mod21|_P5, _mod40|_P6, _mod64|_P1, _mod63|_P2, _mod38|_P3},	// Module 39
{ _HO01R1, _mod21|_P4, _mod22|_P5, _mod41|_P6, _mod65|_P1, _mod64|_P2, _mod39|_P3},	// Module 40
{ _HO01R1, _mod22|_P4, _mod23|_P5, _mod42|_P6, _mod66|_P1, _mod65|_P2, _mod40|_P3},	// Module 41
{ _HO01R1, _mod23|_P4, _mod43|_P5, _mod68|_P6, _mod67|_P1, _mod66|_P2, _mod41|_P3},	// Module 42
{ _HO01R1, _mod24|_P4, _mod44|_P5, _mod69|_P6, _mod68|_P1, _mod42|_P2, _mod23|_P3},	// Module 43
{ _HO01R1, _mod25|_P4, _mod45|_P5, _mod70|_P6, _mod69|_P1, _mod43|_P2, _mod24|_P3},	// Module 44
{ _HO01R1, _mod26|_P4, _mod46|_P5, _mod71|_P6, _mod70|_P1, _mod44|_P2, _mod25|_P3},	// Module 45
{ _HO01R1, _mod47|_P4, _mod73|_P5, _mod72|_P6, _mod71|_P1, _mod45|_P2, _mod26|_P3},	// Module 46
{ _HO01R1, _mod48|_P4, _mod74|_P5, _mod73|_P6, _mod46|_P1, _mod26|_P2, _mod27|_P3},	// Module 47
{ _HO01R1, _mod49|_P4, _mod75|_P5, _mod74|_P6, _mod47|_P1, _mod27|_P2, _mod28|_P3},	// Module 48
{ _HO01R1, _mod50|_P4, _mod76|_P5, _mod75|_P6, _mod48|_P1, _mod28|_P2, _mod29|_P3},	// Module 49
{ _HO01R1, _mod78|_P4, _mod77|_P5, _mod76|_P6, _mod49|_P1, _mod29|_P2, _mod51|_P3},	// Module 50
{ _HO01R1, _mod79|_P4, _mod78|_P5, _mod50|_P6, _mod29|_P1, _mod30|_P2, _mod52|_P3},	// Module 51
{ _HO01R1, _mod80|_P4, _mod79|_P5, _mod51|_P6, _mod30|_P1, _mod31|_P2, _mod53|_P3},	// Module 52
{ _HO01R1, _mod81|_P4, _mod80|_P5, _mod52|_P6, _mod31|_P1, _mod32|_P2, _mod54|_P3},	// Module 53
{ _HO01R1, _mod82|_P4, _mod81|_P5, _mod53|_P6, _mod32|_P1, _mod55|_P2, _mod83|_P3},	// Module 54
{ _HO01R1, _mod83|_P4, _mod54|_P5, _mod32|_P6, _mod33|_P1, _mod56|_P2, _mod84|_P3},	// Module 55
{ _HO01R1, _mod84|_P4, _mod55|_P5, _mod33|_P6, _mod34|_P1, _mod57|_P2, _mod85|_P3},	// Module 56
{ _HO01R1, _mod85|_P4, _mod56|_P5, _mod34|_P6, _mod35|_P1, _mod58|_P2, _mod86|_P3},	// Module 57
{ _HO01R1, _mod86|_P4, _mod57|_P5, _mod35|_P6, _mod59|_P1, _mod88|_P2, _mod87|_P3},	// Module 58
{ _HO01R1, _mod58|_P4, _mod35|_P5, _mod36|_P6, _mod60|_P1, _mod89|_P2, _mod88|_P3},	// Module 59
{ _HO01R1, _mod59|_P4, _mod36|_P5, _mod37|_P6, _mod61|_P1, _mod90|_P2, _mod89|_P3},	// Module 60
{ _HO01R1, _mod60|_P4, _mod37|_P5, _mod20|_P6, _mod38|_P1, _mod91|_P2, _mod90|_P3},	// Module 61
{ _HO01R1, _mod91|_P4, _mod38|_P5, _mod63|_P6, _mod93|_P1, _mod92|_P2, _mod127|_P3},	// Module 62
{ _HO01R1, _mod38|_P4, _mod39|_P5, _mod64|_P6, _mod94|_P1, _mod93|_P2, _mod62|_P3},	// Module 63
{ _HO01R1, _mod39|_P4, _mod40|_P5, _mod65|_P6, _mod95|_P1, _mod94|_P2, _mod63|_P3},	// Module 64
{ _HO01R1, _mod40|_P4, _mod41|_P5, _mod66|_P6, _mod96|_P1, _mod95|_P2, _mod64|_P3},	// Module 65
{ _HO01R1, _mod41|_P4, _mod42|_P5, _mod67|_P6, _mod97|_P1, _mod96|_P2, _mod65|_P3},	// Module 66
{ _HO01R1, _mod42|_P4, _mod68|_P5, _mod99|_P6, _mod98|_P1, _mod97|_P2, _mod66|_P3},	// Module 67
{ _HO01R1, _mod43|_P4, _mod69|_P5, _mod100|_P6, _mod99|_P1, _mod67|_P2, _mod42|_P3},	// Module 68
{ _HO01R1, _mod44|_P4, _mod70|_P5, _mod101|_P6, _mod100|_P1, _mod68|_P2, _mod43|_P3},	// Module 69
{ _HO01R1, _mod45|_P4, _mod71|_P5, _mod102|_P6, _mod101|_P1, _mod69|_P2, _mod44|_P3},	// Module 70
{ _HO01R1, _mod46|_P4, _mod72|_P5, _mod103|_P6, _mod102|_P1, _mod70|_P2, _mod45|_P3},	// Module 71
{ _HO01R1, _mod73|_P4, _mod105|_P5, _mod104|_P6, _mod103|_P1, _mod71|_P2, _mod46|_P3},	// Module 72
{ _HO01R1, _mod74|_P4, _mod106|_P5, _mod105|_P6, _mod72|_P1, _mod46|_P2, _mod47|_P3},	// Module 73
{ _HO01R1, _mod75|_P4, _mod107|_P5, _mod106|_P6, _mod73|_P1, _mod47|_P2, _mod48|_P3},	// Module 74
{ _HO01R1, _mod76|_P4, _mod108|_P5, _mod107|_P6, _mod74|_P1, _mod48|_P2, _mod49|_P3},	// Module 75
{ _HO01R1, _mod77|_P4, _mod109|_P5, _mod108|_P6, _mod75|_P1, _mod49|_P2, _mod50|_P3},	// Module 76
{ _HO01R1, _mod111|_P4, _mod110|_P5, _mod109|_P6, _mod76|_P1, _mod50|_P2, _mod78|_P3},	// Module 77
{ _HO01R1, _mod112|_P4, _mod111|_P5, _mod77|_P6, _mod50|_P1, _mod51|_P2, _mod79|_P3},	// Module 78
{ _HO01R1, _mod113|_P4, _mod112|_P5, _mod78|_P6, _mod51|_P1, _mod52|_P2, _mod80|_P3},	// Module 79
{ _HO01R1, _mod114|_P4, _mod113|_P5, _mod79|_P6, _mod52|_P1, _mod53|_P2, _mod81|_P3},	// Module 80
{ _HO01R1, _mod115|_P4, _mod114|_P5, _mod80|_P6, _mod53|_P1, _mod54|_P2, _mod82|_P3},	// Module 81
{ _HO01R1, _mod116|_P4, _mod115|_P5, _mod81|_P6, _mod54|_P1, _mod83|_P2, _mod117|_P3},	// Module 82
{ _HO01R1, _mod117|_P4, _mod82|_P5, _mod54|_P6, _mod55|_P1, _mod84|_P2, _mod118|_P3},	// Module 83
{ _HO01R1, _mod118|_P4, _mod83|_P5, _mod55|_P6, _mod56|_P1, _mod85|_P2, _mod119|_P3},	// Module 84
{ _HO01R1, _mod119|_P4, _mod84|_P5, _mod56|_P6, _mod57|_P1, _mod86|_P2, _mod120|_P3},	// Module 85
{ _HO01R1, _mod120|_P4, _mod85|_P5, _mod57|_P6, _mod58|_P1, _mod87|_P2, _mod121|_P3},	// Module 86
{ _HO01R1, _mod121|_P4, _mod86|_P5, _mod58|_P6, _mod88|_P1, _mod123|_P2, _mod122|_P3},	// Module 87
{ _HO01R1, _mod87|_P4, _mod58|_P5, _mod59|_P6, _mod89|_P1, _mod124|_P2, _mod123|_P3},	// Module 88
{ _HO01R1, _mod88|_P4, _mod59|_P5, _mod60|_P6, _mod90|_P1, _mod125|_P2, _mod124|_P3},	// Module 89
{ _HO01R1, _mod89|_P4, _mod60|_P5, _mod61|_P6, _mod91|_P1, _mod126|_P2, _mod125|_P3},	// Module 90
{ _HO01R1, _mod90|_P4, _mod61|_P5, _mod38|_P6, _mod62|_P1, _mod127|_P2, _mod126|_P3},	// Module 91
{ _HO01R1, _mod127|_P4, _mod62|_P5, _mod93|_P6, 0, 0, 0},	// Module 92
{ _HO01R1, _mod62|_P4, _mod63|_P5, _mod94|_P6, 0, 0, _mod92|_P3},	// Module 93
{ _HO01R1, _mod63|_P4, _mod64|_P5, _mod95|_P6, 0, 0, _mod93|_P3},	// Module 94
{ _HO01R1, _mod64|_P4, _mod65|_P5, _mod96|_P6, 0, 0, _mod94|_P3},	// Module 95
{ _HO01R1, _mod65|_P4, _mod66|_P5, _mod97|_P6, 0, 0, _mod95|_P3},	// Module 96
{ _HO01R1, _mod66|_P4, _mod67|_P5, _mod98|_P6, 0, 0, _mod96|_P3},	// Module 97
{ _HO01R1, _mod67|_P4, _mod99|_P5, 0, 0, 0, _mod97|_P3},	// Module 98
{ _HO01R1, _mod68|_P4, _mod100|_P5, 0, 0, _mod98|_P2, _mod67|_P3},	// Module 99
{ _HO01R1, _mod69|_P4, _mod101|_P5, 0, 0, _mod99|_P2, _mod68|_P3},	// Module 100
{ _HO01R1, _mod70|_P4, _mod102|_P5, 0, 0, _mod100|_P2, _mod69|_P3},	// Module 101
{ _HO01R1, _mod71|_P4, _mod103|_P5, 0, 0, _mod101|_P2, _mod70|_P3},	// Module 102
{ _HO01R1, _mod72|_P4, _mod104|_P5, 0, 0, _mod102|_P2, _mod71|_P3},	// Module 103
{ _HO01R1, _mod105|_P4, 0, 0, 0, _mod103|_P2, _mod72|_P3},	// Module 104
{ _HO01R1, _mod106|_P4, 0, 0, _mod104|_P1, _mod72|_P2, _mod73|_P3},	// Module 105
{ _HO01R1, _mod107|_P4, 0, 0, _mod105|_P1, _mod73|_P2, _mod74|_P3},	// Module 106
{ _HO01R1, _mod108|_P4, 0, 0, _mod106|_P1, _mod74|_P2, _mod75|_P3},	// Module 107
{ _HO01R1, _mod109|_P4, 0, 0, _mod107|_P1, _mod75|_P2, _mod76|_P3},	// Module 108
{ _HO01R1, _mod110|_P4, 0, 0, _mod108|_P1, _mod76|_P2, _mod77|_P3},	// Module 109
{ _HO01R1, 0, 0, 0, _mod109|_P1, _mod77|_P2, _mod111|_P3},	// Module 110
{ _HO01R1, 0, 0, _mod110|_P6, _mod77|_P1, _mod78|_P2, _mod112|_P3},	// Module 111
{ _HO01R1, 0, 0, _mod111|_P6, _mod78|_P1, _mod79|_P2, _mod113|_P3},	// Module 112
{ _HO01R1, 0, 0, _mod112|_P6, _mod79|_P1, _mod80|_P2, _mod114|_P3},	// Module 113
{ _HO01R1, 0, 0, _mod113|_P6, _mod80|_P1, _mod81|_P2, _mod115|_P3},	// Module 114
{ _HO01R1, 0, 0, _mod114|_P6, _mod81|_P1, _mod82|_P2, _mod116|_P3},	// Module 115
{ _HO01R1, 0, 0, _mod115|_P6, _mod82|_P1, _mod117|_P2, 0},	// Module 116
{ _HO01R1, 0, _mod116|_P5, _mod82|_P6, _mod83|_P1, _mod118|_P2, 0},	// Module 117
{ _HO01R1, 0, _mod117|_P5, _mod83|_P6, _mod84|_P1, _mod119|_P2, 0},	// Module 118
{ _HO01R1, 0, _mod118|_P5, _mod84|_P6, _mod85|_P1, _mod120|_P2, 0},	// Module 119
{ _HO01R1, 0, _mod119|_P5, _mod85|_P6, _mod86|_P1, _mod121|_P2, 0},	// Module 120
{ _HO01R1, 0, _mod120|_P5, _mod86|_P6, _mod87|_P1, _mod122|_P2, 0},	// Module 121
{ _HO01R1, 0, _mod121|_P5, _mod87|_P6, _mod123|_P1, 0, 0},	// Module 122
{ _HO01R1, _mod122|_P4, _mod87|_P5, _mod88|_P6, _mod124|_P1, 0, 0},	// Module 123
{ _HO01R1, _mod123|_P4, _mod88|_P5, _mod89|_P6, _mod125|_P1, 0, 0},	// Module 124
{ _HO01R1, _mod124|_P4, _mod89|_P5, _mod90|_P6, _mod126|_P1, 0, 0},	// Module 125
{ _HO01R1, _mod125|_P4, _mod90|_P5, _mod91|_P6, _mod127|_P1, 0, 0},	// Module 126
{ _HO01R1, _mod126|_P4, _mod91|_P5, _mod62|_P6, _mod92|_P1, 0, 0}    // Module 127
};

/************************ (C) COPYRIGHT OU *****END OF FILE****/
